### PR TITLE
Implemented Builder Pattern with regards to issue #8

### PR DESCRIPTION
**Pull request by NdubuisiJr**
Sorry for the miss-spelled "issue" on the commit message.

Check out my implementation of the builder creational design pattern. It makes the client code very simple. And the usage is quite intuitive.

### CODE REVIEW

**Comment by abishekaditya** [comment]
Looks good, I will test it once tonight. Can you modify the structure so that it is not BuilderPattern/BuilderPattern but only BuilderPattern

**Comment by NdubuisiJr** [comment]
Okay... I will modify the directory structure

**Comment by NdubuisiJr** [comment]
I have changed the folder structure

**Comment by NdubuisiJr** [comment]
I have also implemented the Chain of Responsibility design pattern

**Pull request merged**
